### ISSUE TITLE
Question: Intersects with polygon

### ISSUE THREAD

**Issue by josebalius** [tidwall/buntdb#13]
Is it somehow possible to intersect queries with polygons? Do i have to create a custom indexer for that?

Thanks!

**Comment by tidwall** [comment]
It's not available today but I plan on having this feature in very near future. 

You will need to create a custom indexer and then filter out the intersecting polygons from inside the `Intersects` call.

For example, you could use the [GeoJSON](https://godoc.org/github.com/tidwall/tile38/geojson) library from the Tile38 project:

```go

func IndexGeoJSON(a string) (min, max []float64) {
	o, err := geojson.ObjectJSON(a)
	if err != nil {
		return []float64{0, 0}, []float64{0, 0}
	}
	bbox := o.CalculatedBBox()
	return []float64{bbox.Min.X, bbox.Min.Y}, []float64{bbox.Max.X, bbox.Max.Y}
}

db.CreateSpatialIndex("poly", "poly:*", IndexGeoJSON) 

polyJSON := `{"type":"Polygon","coordinates":[...]}`

var intersectingKeys []string
polyObj, err := geojson.ObjectJSON(poly)
if err == nil {
	db.View(func(tx *buntdb.Tx) error {
		tx.Intersects("poly", polyJSON, func(key, val string) bool {
			valObj, err := geojson.ObjectJSON(val)
			if err == nil && valObj.Intersects(polyObj) {
				intersectingKeys = append(intersectingKeys, key)
			}
			return true
		})
		return nil
	})
}
```

**Comment by josebalius** [comment]
@tidwall awesome, yeah i started going down this path, i am generating an envelope/bbox for the poly, querying the points, and then filtering points that fall outside of the poly shape. Perf seems fine but it would be awesome to support it out of the box. 

Let me know if i can help.

**Comment by tidwall** [comment]
I'm looking at creating a spatial index interface that handles Intersects, Within, and Nearby. I would likely provide GeoJSON and Well-Known Text/Binary out of the box. But the interface would allow for any format such as Topo or KML.

I'll keep you posted on progress.

**Comment by eminden** [comment]
@tidwall any news regarding this development?

**Comment by tidwall** [comment]
@eminden I got nothing at this time. Sorry. :(

**Comment by eminden** [comment]
I need k-nearest queries, is it possible to do it somehow on the current implementation?

**Comment by tidwall** [comment]
This issue is pretty old so I'm closing it. 
I've wanted to add more geospatial functionality but I just haven't found the time to do so.
Feel free to reopen if needed.

Thanks!
