### ISSUE TITLE
Case insensitive match

### ISSUE THREAD

**Issue by yiiton** [tidwall/buntdb#14]
Hi, is it possible to match key+"*" in case insensitive mode? Thanks

**Comment by tidwall** [comment]
Do you mean matching keys when adding to indexes? 

This is not currently. Perhaps I could add an options to CreateIndex that allow for specifying case-insensitive pattern matching. Would something like this work?

```
opts := buntdb.IndexOptions{
        CaseInsensitiveKeyMatching: true,
}
buntdb.CreateIndexOptions("myindex", "user:*", &opts, buntdb.IndexString)
```

**Comment by yiiton** [comment]
Exactly, that would be great

**Comment by tidwall** [comment]
I just pushed this feature to the master branch. It works as described above with the exception that  the index must be created in a transaction:

```go
db.Update(func(tx *buntdb.Tx) error{
        opts := buntdb.IndexOptions{
                CaseInsensitiveKeyMatching: true,
        }
        return tx.CreateIndexOptions("myindex", "user:*", &opts, buntdb.IndexString)
})
```
