### ISSUE TITLE
Export db.Begin function

### ISSUE THREAD

**Issue by sergeyt** [tidwall/buntdb#16]
This one easy to do and allows controlling transaction inside application.

**Comment by tidwall** [comment]
Hi @sergeyt, Sorry about the delayed response. 

I chose not to include export `db.Begin` and `db.Commit/Rollback` in favor of using the managed functions `db.Update/View`. Using the managed functions minimize risk of deadlocks and I didn't see an advantage with exporting. But maybe I'm overlooking something.

**Comment by sergeyt** [comment]
Hi @tidwall, I agree that the use case to use `db.Begin` directly is uncommon. But it might be used in the library like my [nosql](https://github.com/gocontrib/nosql) where the underlying storage is abstracted over unified interface. Initially I've wrapped [boltdb](https://github.com/boltdb/bolt) that has explicit `db.Begin` function. Anyway I think it is still feasible to implement `nosql` interface over BuntDB API.

**Comment by sergeyt** [comment]
[upper.io](https://upper.io/db.v2/) also has `Tx` transaction interface.

**Comment by tidwall** [comment]
Hi @sergeyt,

I finally got around to exporting the those function. Let me know if you run into any problems. Thanks for the suggestion.

**Comment by sergeyt** [comment]
Hi @tidwall. Great, thank you!
