### ISSUE TITLE
How to use "pivot" value in AscendGreaterOrEqual func

### ISSUE THREAD

**Issue by korjavin** [tidwall/buntdb#22]
I wrote this part of code, please take a look.
I created a custom index, on json field, and trying to iterate over it.
I expect to get exactly two values of that iteration, but always get three.

There is the code for test case: 
https://gist.github.com/e5488c8efd08092673f2553bc83d2e83

**Comment by tidwall** [comment]
Try this pivot `{"Statuses":[{"Sid":6,"Time":"2016-03-17T12:58:03Z"}]}`

**Comment by korjavin** [comment]
When you wrote that, it looks so obvious and logical!

I am sorry for a stupid question, and thank you!

**Comment by tidwall** [comment]
You're welcome. :)
