### ISSUE TITLE
Delete inside iterator

### ISSUE THREAD

**Issue by logrusorgru** [tidwall/buntdb#24]
```go
tx.AscendKeys("object:*", func(k, v string) bool {
	if someCondition(k) == true {
		if _, err = tx.Delete(k); err != nil {

                            // got: "tx is iterating" error here

			return false // break
		}
	}
	return true // continue
})
```

Is there a way to Delete inside iterator?

**Comment by logrusorgru** [comment]
If not then it is "feature request".

**Comment by tidwall** [comment]
This is a feature that I would like too and I hope to add it in the future.

Here's a workaround that I use:

```go
var delkeys []string
tx.AscendKeys("object:*", func(k, v string) bool {
	if someCondition(k) == true {
		delkeys = append(delkeys, k)
	}
	return true // continue
})
for _, k := range delkeys {
	if _, err = tx.Delete(k); err != nil {
		return err
	}
}
```

**Comment by tidwall** [comment]
I'm closing this issue for now as I haven't found the time to add this functionality. I may come back to this issue the future. In the meantime I added the workaround to the README in hopes that other may find is useful.

Feel free to reopen if needed.

Thanks!
