### ISSUE TITLE
NEARBY

### ISSUE THREAD

**Issue by leearmstrong** [tidwall/buntdb#31]
I see that tile38 supports a NEARBY query, is that possible at all with buntdb?

http://tile38.com/commands/nearby/

**Comment by tidwall** [comment]
Right now BuntDB is limited to intersection searches on rectangles and points.

If what you are wanting is to find all points that are within a specified radius, such as:

<img src="https://user-images.githubusercontent.com/1156077/34844875-2db06570-f6d0-11e7-9256-84db03561849.png" width="368" height="368">

Then may I suggest this approach.

## 1. Calculate the bounding box around the circle

<img src="https://user-images.githubusercontent.com/1156077/34845041-daf29f3c-f6d0-11e7-87fd-2a9eb38c75c2.png" width="368" height="368">

## 2. Get all the points in the rectangle

<img src="https://user-images.githubusercontent.com/1156077/34845389-ebf11c40-f6d1-11e7-8e23-2eb8864f415e.png" width="368" height="368">

## 3. Perform the haversine calculation on each point

<img src="https://user-images.githubusercontent.com/1156077/34845438-138f3ed0-f6d2-11e7-972d-0a8e7fe7ad6b.png" width="368" height="368">

----

This is pretty much how Tile38 does it. Below is some code that you might find helpful.

[Calculate Bounds of a Geo Circle](https://gist.github.com/tidwall/efb16b27e3ef87ba96e05ebbb94c6a3b)
[Haversine Formula](https://github.com/tidwall/tile38/blob/d45eb6f92d90bbcc7980dd5cfc7afa7ae07742e9/geojson/geo/geo.go#L11-L21)

**Comment by leearmstrong** [comment]
Thanks for the feedback. I’m actually just after the nearest point so might just look at implementing a kd-tree instead. 

I thought Tile38 did that sort of query?

**Comment by tidwall** [comment]
Ah. At the moment BuntDB doesn’t have a kNN operation.

**Comment by leearmstrong** [comment]
Thanks @tidwall, tile38 does at the moment doesn't it?  

To use this I suppose I'd need to port the R-Tree across to BuntDB?

**Comment by tidwall** [comment]
Yes, Tile38 has support for kNN searches.

BuntDB uses an R-Tree already, so it’s possible to add kNN without modifying the underlying data structure. I just haven’t gotten around to adding the operation yet.

**Comment by leearmstrong** [comment]
Ok thanks, will fork away 👍

**Comment by tidwall** [comment]
Sounds good. A couple of pointers. 

BuntDB uses this R-Tree package.
https://github.com/tidwall/rtree

Tile38 uses this one and includes the kNN code
https://github.com/tidwall/tile38/tree/master/index/

They have an entirely different codebases.
Tile38 rtree is strictly 2 dimensions while the BuntDB is a composite of 20 dimensions.

**Comment by leearmstrong** [comment]
Wow, 20!!!  For a lat/lon I'll only need the 2 dimensions.

I'll see if I can tackle it but suspect I might end up just creating a bounding box around my test point and do a check and sort them by distance that way

**Comment by tidwall** [comment]
I just updated the https://github.com/tidwall/rtree project to include kNN support. And I added a `Nearby` function to BuntDB.

**Comment by leearmstrong** [comment]
Oh nice, thank you that is awesome.  I had started a kd-tree implementation and then realised it was suited to a curved globe!

**Comment by tidwall** [comment]
You're welcome.  :)

**Comment by leearmstrong** [comment]
What value is the distance operator?

I created a real simple example...
https://gist.github.com/leearmstrong/8ff311e5ffb4e6075e24f31737f2c06d

This logs 

> 2018/01/15 10:53:37 Searching from coord [-0.919 50.819]
> 2018/01/15 10:53:37 aircraft:TEST:pos [-0.919 50.919] 0.009999999999998864

I make the distance 11km.

Is the distance not relative but I can be guaranteed they will be returned in order and I need to calculate the distance myself?

**Comment by tidwall** [comment]
The distance param could use a little more description, or maybe I should just removed it to avoid confusion.

It's the distance of the bounding boxes. In your case it's the distance of the two 2D points squared. The unit is the same as what was inputed, in your case degrees (lat/lon).

To get the distance on earth in meters (not in degrees) you should ignore the distance and calculate using haversine yourself.

```go
bunt.View(func(tx *buntdb.Tx) error {
	tx.Nearby("locationIndex", locationString, func(key, val string, dist float64) bool {
		meters := haversine(locationString, val)
		return false
	})
	return nil
})
```

**Comment by leearmstrong** [comment]
Thanks for clarifying. I suspect it could be useful in just a normal x,y
grid giving a true distance so worth leaving?

**Comment by tidwall** [comment]
You're welcome. I'll just leave it for now and try to come up with a better description.

**Comment by tidwall** [comment]
I added a description of the dist param to the Nearby function comment.
