### ISSUE TITLE
Is it in-memory db?

### ISSUE THREAD

**Issue by hadi2f244** [tidwall/buntdb#35]
I worked with [boltdb](https://github.com/boltdb/bolt),it's like Buntdb. As mentioned in Documentation buntdb is an in-memory database(while boltdb isn't). 
So can it manage write(on-disk) operation faster than disk memory DBs?(Does it use any in-memory middle cache and write queue?)

**Comment by tidwall** [comment]
> Is it in-memory db?

Yes, buntdb is entirely in-memory. 

> So can it manage write(on-disk) operation faster than disk memory DBs?

Yes, the data is persisted to disk as an append-only file, which has fast writes.

> Does it use any in-memory middle cache and write queue?

No, all mutable operations are written directly to disk.

**Comment by xcl3721** [comment]
how large data can index,i have 128GB data for index

**Comment by gedw99** [comment]
Any plans to support using the RAM as a cache.
In other works if the DB is bigger than the RAM available you can still use it.
If a key that is meant to be in RAM is not there then it fetches it.
Basically you end up holding the meta data and keys in memory and the actual json data rows on disk.
