### ISSUE TITLE
Advice? Slow JSON unmarshalling because of string -> []bytes

### ISSUE THREAD

**Issue by jpincas** [tidwall/buntdb#38]
I wonder if anyone can offer any advice.

I've been doing extensive benchmarking of different Go KV stores for an ERP application.  I am saving millions of 'transactions' serialised with JSON, reading them back, deserialising and running some aggregation operations.  

I was comparing Bunt to BadgerDB and finding that Badger was 4x faster for my benchmark for reading and aggregating, which seemed odd to me.

After a little digging, I realised that if I removed the JSON unmarshalling step, Bunt became 2x faster than Badger.  Obviously I am using the same JSON unmarshalling technique in both cases.

The problem lies in the fact that Bunt returns strings whereas Badger returns `[]byte`.  This introduces another step in the deserialisation for Bunt `json.Unmarshal([]byte(value), &order)` which is what is causing the slowdown on the Bunt benchmark.

Ive Googled about a bit and understand that the string -> []byte conversion is costly, and have come across some solutions involving `unsafe`, but haven't been able to get them to work for me.

Has anyone tackled this issue and come up with a good solution. BadgerDB is really nice, but Bunt's indexing functionality is just what I'm looking for and would really love to choose it for this project.  I can see that the raw iteration speed is faster than Badger - its just this string issue thats causing the slower aggregation.

**Comment by jpincas** [comment]
For reference, I've tried converting to bytes like this, but I get a `panic: runtime error: slice bounds out of range` at some point in the loop:

```
func stringToBytes(s *string) []byte {
	return *(*[]byte)(unsafe.Pointer(s))
}
```

**Comment by valinurovam** [comment]
I think only solution is fork or make PR with some changes to work buntdb with slice of bytes than raw strings. Cause internally it use anyway bytes as u can see here https://github.com/tidwall/buntdb/blob/master/buntdb.go#L1218

**Comment by jpincas** [comment]
Oh yeah - you're right.  I wonder what the motivation behind having `string` in the api was.  Presumably that was for a good reason.

**Comment by tidwall** [comment]
>  I wonder what the motivation behind having string in the api was. Presumably that was for a good reason.

Strings are used instead of bytes because the database is in-memory and strings avoids any chance of accidental mutations to the base values. For example, with []byte values, it could be possible to call `val := tx.Get("mykey")` and then change the byte at some arbitrary position and break the ordering of the indexing. 

This is less of an issue with on-disk databases because `Get` operations commonly retrieve from disk and load into memory for a short period of time. Changes to the memory would likely not corrupt the value in that persists on disk.

----

Your stringToBytes is casting types of two different sizes. string is 2 words and []bytes is 3 words. This may work better:

```go
func stringToBytes(s string) []byte {
	return *(*[]byte)(unsafe.Pointer(&reflect.SliceHeader{
		(*reflect.StringHeader)(unsafe.Pointer(&s)).Data,
		len(s), len(s),
	}))
}
```

**Comment by jpincas** [comment]
Thanks so much.  Could I be cheeky and ask for the correct function for the inverse operation - this is a little too low level for me!!

**Comment by tidwall** [comment]
Just swap out the StringHeader/SliceHeader and string/[]byte. Also a StringHeader takes 2 words which is the Data and Len fields, while the SliceHeader has Data, Len, and Cap.

```go
func bytesToString(b []byte) string {
    return *(*string)(unsafe.Pointer(&reflect.StringHeader{
        (*reflect.SliceHeader)(unsafe.Pointer(&b)).Data, len(b),
    }))
}
```

**Comment by jpincas** [comment]
Superb - looking forward to plugging this improved conversion into the benchmarks.  I bet it will improve the iteration speed massively.

**Comment by Nicolab** [comment]
Hello,

@jpincas you have a best result with the `stringToBytes`?

**Comment by jpincas** [comment]
Actually it didn't seem to make a whole lot of difference.  I think it might be the case that Go optimises this under the hood.

**Comment by Nicolab** [comment]
Ok interesting, thank you for your reply :+1:

**Comment by tidwall** [comment]
I’m closing this issue for now. Feel free to reopen if you find a specific issue that needs addressing. Thanks.
