### ISSUE TITLE
Does pattern del disk val supported?

### ISSUE THREAD

**Issue by lvchengchang** [tidwall/buntdb#48]
look source code, i find if delete btree value.program append del value in disk. long time! disk size very big!I think use pattern handle update and del.

**Comment by tidwall** [comment]
No, each object that is deleted is appended to the log file. 

The log file does automatically shrink periodically in the background.

From the README:

> As you may guess this log file can grow large over time. There's a background routine that automatically shrinks the log file when it gets too large. There is also a Shrink() function which will rewrite the aof file so that it contains only the items in the database. The shrink operation does not lock up the database so read and write transactions can continue while shrinking is in process.

**Comment by lvchengchang** [comment]
ok, good way
