### ISSUE TITLE
Invalid descend range result

### ISSUE THREAD

**Issue by GreatMartial** [tidwall/buntdb#54]
hello, tidwall
I hoped to get the ascend results is right  when I was using tx.AscendRange or tx.DescendRange fuction. 
But when i hoped to get the descend results, it's nil of return.
Can you help me? thanks.

```
db, _ := buntdb.Open(":memory:")
	db.Update(func(tx *buntdb.Tx) error {
		tx.CreateIndex("last_name", "*", buntdb.IndexJSON("name.last"))
		
		tx.Set("1", `{"name":{"first":"Tom","last":"Johnson"},"age":"38"}`, nil)
		tx.Set("2", `{"name":{"first":"Janet","last":"Prichard"},"age":"47"}`, nil)
		tx.Set("3", `{"name":{"first":"Carol","last":"Anderson"},"age":"52"}`, nil)
		tx.Set("4", `{"name":{"first":"Alan","last":"Cooper"},"age":"28"}`, nil)
		tx.Set("5", `{"name":{"first":"Jack","last":"Ma"},"age":"20"}`, nil)
		tx.Set("6", `{"name":{"first":"Blues","last":"Li"},"age":"31"}`, nil)
		tx.Set("7", `{"name":{"first":"Pony","last":"Ma"},"age":"3"}`, nil)
		tx.Set("8", `{"name":{"first":"Robin","last":"Li"},"age":"2"}`, nil)
		tx.Set("9", `{"name":{"first":"Larry","last":"Liu"},"age":""}`, nil)
		return nil
	})

	db.View(func(tx *buntdb.Tx) error {
		fmt.Println("---------------------")
		tx.Descend("last_name", func(key, value string) bool {
			fmt.Printf("%s: %s\n", key, value)
			return true
		})
		
		fmt.Println("---------------------")
		tx.DescendRange("last_name", `{"name":{"last":""}}`, `{"name":{"last":"Ma"}}`, func(key, value string) bool {
			fmt.Printf("%s: %s\n", key, value)
			return true
		})
		return nil
	})
```
result:
```
---------------------
2: {"name":{"first":"Janet","last":"Prichard"},"age":"47"}
7: {"name":{"first":"Pony","last":"Ma"},"age":"3"}
5: {"name":{"first":"Jack","last":"Ma"},"age":"20"}
9: {"name":{"first":"Larry","last":"Liu"},"age":""}
8: {"name":{"first":"Robin","last":"Li"},"age":"2"}
6: {"name":{"first":"Blues","last":"Li"},"age":"31"}
1: {"name":{"first":"Tom","last":"Johnson"},"age":"38"}
4: {"name":{"first":"Alan","last":"Cooper"},"age":"28"}
3: {"name":{"first":"Carol","last":"Anderson"},"age":"52"}
---------------------
```

```tx.CreateIndex("last_name", "*", buntdb.IndexJSON("name.last")```
replace
```tx.CreateIndex("last_name", "*", buntdb.Desc(buntdb.IndexJSON("name.last")))```		

result:
```
---------------------
3: {"name":{"first":"Carol","last":"Anderson"},"age":"52"}
4: {"name":{"first":"Alan","last":"Cooper"},"age":"28"}
1: {"name":{"first":"Tom","last":"Johnson"},"age":"38"}
8: {"name":{"first":"Robin","last":"Li"},"age":"2"}
6: {"name":{"first":"Blues","last":"Li"},"age":"31"}
9: {"name":{"first":"Larry","last":"Liu"},"age":""}
7: {"name":{"first":"Pony","last":"Ma"},"age":"3"}
5: {"name":{"first":"Jack","last":"Ma"},"age":"20"}
2: {"name":{"first":"Janet","last":"Prichard"},"age":"47"}
---------------------
3: {"name":{"first":"Carol","last":"Anderson"},"age":"52"}
4: {"name":{"first":"Alan","last":"Cooper"},"age":"28"}
1: {"name":{"first":"Tom","last":"Johnson"},"age":"38"}
8: {"name":{"first":"Robin","last":"Li"},"age":"2"}
6: {"name":{"first":"Blues","last":"Li"},"age":"31"}
9: {"name":{"first":"Larry","last":"Liu"},"age":""}

**Comment by tidwall** [comment]
The DescendRange signature is

```go
DescendRange(index, lessOrEqual, greaterThan string, iterator func(key, value string) bool) error
```

So the line in your code:

```go
tx.DescendRange("last_name", `{"name":{"last":""}}`, `{"name":{"last":"Ma"}}`, func(key, value string) bool {
```

should be 

```go
tx.DescendRange("last_name", `{"name":{"last":"Ma"}}`, `{"name":{"last":""}}`, func(key, value string) bool {
```

----

The `buntdb.Desc` function inverses the `Ascend*` and `Descend*` params and results.

For example:

```go
db, _ := buntdb.Open(":memory:")
db.Update(func(tx *buntdb.Tx) error {
	tx.CreateIndex("last_name", "*", buntdb.Desc(buntdb.IndexJSON("name.last")))

	tx.Set("1", `{"name":{"first":"Tom","last":"Johnson"},"age":"38"}`, nil)
	tx.Set("2", `{"name":{"first":"Janet","last":"Prichard"},"age":"47"}`, nil)
	tx.Set("3", `{"name":{"first":"Carol","last":"Anderson"},"age":"52"}`, nil)
	tx.Set("4", `{"name":{"first":"Alan","last":"Cooper"},"age":"28"}`, nil)
	tx.Set("5", `{"name":{"first":"Jack","last":"Ma"},"age":"20"}`, nil)
	tx.Set("6", `{"name":{"first":"Blues","last":"Li"},"age":"31"}`, nil)
	tx.Set("7", `{"name":{"first":"Pony","last":"Ma"},"age":"3"}`, nil)
	tx.Set("8", `{"name":{"first":"Robin","last":"Li"},"age":"2"}`, nil)
	tx.Set("9", `{"name":{"first":"Larry","last":"Liu"},"age":""}`, nil)
	return nil
})

db.View(func(tx *buntdb.Tx) error {
	fmt.Println("---------------------")
	tx.Ascend("last_name", func(key, value string) bool {
		fmt.Printf("%s: %s\n", key, value)
		return true
	})

	fmt.Println("---------------------")
	tx.AscendRange("last_name", `{"name":{"last":"Ma"}}`, `{"name":{"last":""}}`, func(key, value string) bool {
		fmt.Printf("%s: %s\n", key, value)
		return true
	})
	return nil
})
```

returns 

```
2: {"name":{"first":"Janet","last":"Prichard"},"age":"47"}
5: {"name":{"first":"Jack","last":"Ma"},"age":"20"}
7: {"name":{"first":"Pony","last":"Ma"},"age":"3"}
9: {"name":{"first":"Larry","last":"Liu"},"age":""}
6: {"name":{"first":"Blues","last":"Li"},"age":"31"}
8: {"name":{"first":"Robin","last":"Li"},"age":"2"}
1: {"name":{"first":"Tom","last":"Johnson"},"age":"38"}
4: {"name":{"first":"Alan","last":"Cooper"},"age":"28"}
3: {"name":{"first":"Carol","last":"Anderson"},"age":"52"}
---------------------
5: {"name":{"first":"Jack","last":"Ma"},"age":"20"}
7: {"name":{"first":"Pony","last":"Ma"},"age":"3"}
9: {"name":{"first":"Larry","last":"Liu"},"age":""}
6: {"name":{"first":"Blues","last":"Li"},"age":"31"}
8: {"name":{"first":"Robin","last":"Li"},"age":"2"}
1: {"name":{"first":"Tom","last":"Johnson"},"age":"38"}
4: {"name":{"first":"Alan","last":"Cooper"},"age":"28"}
3: {"name":{"first":"Carol","last":"Anderson"},"age":"52"}
```

**Comment by GreatMartial** [comment]
It turned out that because of carelessness, I read the wrong order of passing parameters.
this small problem still needs your help answer, i am very sorry.
Finally,thank you for your help.

**Comment by GreatMartial** [comment]
> The DescendRange signature is
> 
> ```go
> DescendRange(index, lessOrEqual, greaterThan string, iterator func(key, value string) bool) error
> ```
> 
> So the line in your code:
> 
> ```go
> tx.DescendRange("last_name", `{"name":{"last":""}}`, `{"name":{"last":"Ma"}}`, func(key, value string) bool {
> ```
> 
> should be
> 
> ```go
> tx.DescendRange("last_name", `{"name":{"last":"Ma"}}`, `{"name":{"last":""}}`, func(key, value string) bool {
> ```
> 
> The `buntdb.Desc` function inverses the `Ascend*` and `Descend*` params and results.
> 
> For example:
> 
> ```go
> db, _ := buntdb.Open(":memory:")
> db.Update(func(tx *buntdb.Tx) error {
> 	tx.CreateIndex("last_name", "*", buntdb.Desc(buntdb.IndexJSON("name.last")))
> 
> 	tx.Set("1", `{"name":{"first":"Tom","last":"Johnson"},"age":"38"}`, nil)
> 	tx.Set("2", `{"name":{"first":"Janet","last":"Prichard"},"age":"47"}`, nil)
> 	tx.Set("3", `{"name":{"first":"Carol","last":"Anderson"},"age":"52"}`, nil)
> 	tx.Set("4", `{"name":{"first":"Alan","last":"Cooper"},"age":"28"}`, nil)
> 	tx.Set("5", `{"name":{"first":"Jack","last":"Ma"},"age":"20"}`, nil)
> 	tx.Set("6", `{"name":{"first":"Blues","last":"Li"},"age":"31"}`, nil)
> 	tx.Set("7", `{"name":{"first":"Pony","last":"Ma"},"age":"3"}`, nil)
> 	tx.Set("8", `{"name":{"first":"Robin","last":"Li"},"age":"2"}`, nil)
> 	tx.Set("9", `{"name":{"first":"Larry","last":"Liu"},"age":""}`, nil)
> 	return nil
> })
> 
> db.View(func(tx *buntdb.Tx) error {
> 	fmt.Println("---------------------")
> 	tx.Ascend("last_name", func(key, value string) bool {
> 		fmt.Printf("%s: %s\n", key, value)
> 		return true
> 	})
> 
> 	fmt.Println("---------------------")
> 	tx.AscendRange("last_name", `{"name":{"last":"Ma"}}`, `{"name":{"last":""}}`, func(key, value string) bool {
> 		fmt.Printf("%s: %s\n", key, value)
> 		return true
> 	})
> 	return nil
> })
> ```
> 
> returns
> 
> ```
> 2: {"name":{"first":"Janet","last":"Prichard"},"age":"47"}
> 5: {"name":{"first":"Jack","last":"Ma"},"age":"20"}
> 7: {"name":{"first":"Pony","last":"Ma"},"age":"3"}
> 9: {"name":{"first":"Larry","last":"Liu"},"age":""}
> 6: {"name":{"first":"Blues","last":"Li"},"age":"31"}
> 8: {"name":{"first":"Robin","last":"Li"},"age":"2"}
> 1: {"name":{"first":"Tom","last":"Johnson"},"age":"38"}
> 4: {"name":{"first":"Alan","last":"Cooper"},"age":"28"}
> 3: {"name":{"first":"Carol","last":"Anderson"},"age":"52"}
> ---------------------
> 5: {"name":{"first":"Jack","last":"Ma"},"age":"20"}
> 7: {"name":{"first":"Pony","last":"Ma"},"age":"3"}
> 9: {"name":{"first":"Larry","last":"Liu"},"age":""}
> 6: {"name":{"first":"Blues","last":"Li"},"age":"31"}
> 8: {"name":{"first":"Robin","last":"Li"},"age":"2"}
> 1: {"name":{"first":"Tom","last":"Johnson"},"age":"38"}
> 4: {"name":{"first":"Alan","last":"Cooper"},"age":"28"}
> 3: {"name":{"first":"Carol","last":"Anderson"},"age":"52"}
> ```

**Comment by tidwall** [comment]
No worries. I’m happy to help. :)
