### ISSUE TITLE
Attempting to use AscendEqual

### ISSUE THREAD

**Issue by haasted** [tidwall/buntdb#55]
I'm trying to use the `AscendEqual` function to iterate through entries, but it's not returning the results I'm expecting. I've narrowed the issue down to the following large-ish (sorry) test case:

```go
func TestNameEquals(t *testing.T) {
	iter := func(key, value string) bool {
		i, _ := strconv.Atoi(key)
		fmt.Printf("%2d - %v\n", i, value)
		return true
	}

	j := func(v string, a int) string {
		return fmt.Sprintf("{\"name\":\"%v\", \"age\":%v}", v, a)
	}

	name := func(v string) string {
		return fmt.Sprintf("{\"name\":\"%v\"}", v)
	}

	db, _ := buntdb.Open(":memory:")
	db.CreateIndex("name", "*",
		buntdb.IndexJSON("name"),
		buntdb.IndexJSON("age"),
	)
	db.Update(func(tx *buntdb.Tx) error {
		tx.Set("1", j("bob", 42), nil)
		tx.Set("2", j("james", 55), nil)
		tx.Set("4", j("logan", 14), nil)
		tx.Set("11", j("james", 11), nil)
		tx.Set("3", j("clark", 33), nil)
		tx.Set("5", j("tommy", 15), nil)
		tx.Set("6", j("zane", 19), nil)
		return nil
	})

	db.View(func(tx *buntdb.Tx) error {
		fmt.Println(" -- Greater than d")
		tx.AscendGreaterOrEqual("name", name("d"), iter)

		fmt.Println(" -- Equals James")
		tx.AscendEqual("name", name("james"), iter)

		return nil
	})
}
```

The output from running the test case is:
```
=== RUN   TestNameEquals
 -- Greater than d
11 - {"name":"james", "age":11}
 2 - {"name":"james", "age":55}
 4 - {"name":"logan", "age":14}
 5 - {"name":"tommy", "age":15}
 6 - {"name":"zane", "age":19}
 -- Equals James
--- PASS: TestNameEquals (0.00s)
```

`AscendGreaterOrEqual` works exactly as expected, but I was hoping that `AscendEqual` would allow me to iterate only the `james` entries sorted by the `age` field. Have I misunderstood the purpose of the function?

**Comment by haasted** [comment]
Worked a bit more and realized the following (which I perhaps should have caught earlier): Removing the second index makes the `AscendEqual` work as expected. Alternatively, including the `age` field in the search term also yields results.

Is there some way to make `AscendEqual` treat an omitted field in the search term as "wildcard", ie. I do not care about this value?

**Comment by tidwall** [comment]
> Is there some way to make AscendEqual treat an omitted field in the search term as "wildcard", ie. I do not care about this value? 

I don’t think that that is possible with AscendEqual. It’s meant to grab exact matches.

One idea is to use AscendGreaterOrEqual, which will jump you to the first candidate. Then, from inside the iteration function, do a custom comparison on each item, and then break out of the iterator moves past the possible range. 

This is basically how the AscendEquals works. It uses AscendGreaterOrEquals in the hood, and it’s comparison is looking for an exact match.

**Comment by haasted** [comment]
Thanks for the prompt and helpful reply. Definitely the solution to use.

Just for fun, I also tried to implement an "optional" JSON index, which will not match in case any of the JSON paths offered do not exist. Using that does actually seem to have solved my issue, although I'm not completely sure that I haven't violated the contract of the comparison function in the most obscene way possible or missed some test cases that will break functionality. :) 

```
func IndexJSONOptional(path string) func(a, b string) bool {
	return func(a, b string) bool {
		opa := gjson.Get(a, path)
		opb := gjson.Get(b, path)

		if !opa.Exists() || !opb.Exists() {
			return false
		}

		return opa.Less(opb, false)
	}
}
```

**Comment by tmazeika** [comment]
@haasted I came up with a similar solution to your `IndexJSONOptional` and I think that it should be fine. But given my brief experiments, it looks like it only works when all optional indices appear last in the multi-index list. I wouldn't really be able to say exactly why, though.
