### ISSUE TITLE
How to save one key with multiple values?

### ISSUE THREAD

**Issue by smartaquarius10** [tidwall/buntdb#65]
Hello,

I have an XML of this structure and I want to transfer its data to Bunt DB

```
<MonitoringApps>
    <VD Id="XYZ">
        <ClientId>123456789</ClientId>
        <ClientSecret>0987654321</ClientSecret>
    </VD>
</MonitoringApps>

```
As it is shown per VD id we have one client id and one secret. Is there any way to save the VD id as key and others as 2 values of it in the DB.

**Comment by tidwall** [comment]
I added searching and indexed of JSON documents, but I didn't write anything for XML. BuntDB will accept whatever you give it, but you'll have to write your own XML indexing functions.
