### ISSUE TITLE
strconv.ParseInt: parsing "18446744073709551612": value out of range 

### ISSUE THREAD

**Issue by ghostiam** [tidwall/buntdb#68]
Parses as int64:
https://github.com/tidwall/buntdb/blob/18423895fce43b4b92a54d4d515bf64870227f7d/buntdb.go#L864
But saves as uint64:
https://github.com/tidwall/buntdb/blob/18423895fce43b4b92a54d4d515bf64870227f7d/buntdb.go#L1225

![Снимок экрана 2020-12-10 в 20 06 48](https://user-images.githubusercontent.com/12181586/101764347-50c64f80-3b23-11eb-8fc7-c029e28303f3.jpg)

**Comment by tidwall** [comment]
Thanks!
