### ISSUE TITLE
Index less function called for unmatched keys

### ISSUE THREAD

**Issue by hallerm** [tidwall/buntdb#76]
The replace and delete paths do not use the matcher in the index and will thus pass keys not covered by the index pattern to its less function. This requires extra care and defensiveness to write a robust less function with heterogenous values. A PR that fixes this is at https://github.com/tidwall/buntdb/pull/75.

**Comment by tidwall** [comment]
I just merged the #75 and pushed a new version. 

Thanks a ton!
