### ISSUE TITLE
documentation mark and question 

### ISSUE THREAD

**Issue by k0mrade** [tidwall/buntdb#9]
Hi,

2D point: [10 15 12]
this will be 
2D point: [10 15].

Question: Is it possible/correct to use the 2D point spatial index as data time range?
For example, [startTime stopTime] UnixNano --> int64 as XY.

**Comment by tidwall** [comment]
Thanks for finding the typo. Just fixed the README.

A spatial index is not limited to XY points. You can store any type of ranged numerical data. So `[startTime stopTime]` will work.

**Comment by k0mrade** [comment]
Hi Josh,

Bunt doesn't implement to save indexes into a database file now, is it? I tested the database with ~ 10e6 keys today. File size is ~ 1Gb. Indexes are fast, great work. But IndexString preparation takes ~ 90 sec if indexes are key based and hours if I use IndexJSON on value. Is the way to save BTree to file and read it? Are there hidden internal restrictions?

**Comment by tidwall** [comment]
Hi Dmitry,

> Bunt doesn't implement to save indexes into a database file now, is it?

That's right, indexes are rebuilt each time the database is opened. The database file is an [append only file](https://github.com/tidwall/buntdb#append-only-file) that's just a series of Set and Delete commands that are played back in the order that they were called.

> I tested the database with ~ 10e6 keys today. File size is ~ 1Gb. Indexes are fast, great work. But IndexString preparation takes ~ 90 sec if indexes are key based and hours if I use IndexJSON on value.

For all Bunt databases there is a single BTree for all the keys and then one BTree for each index. Processing the Keys BTree is a very simple binary comparison on the key strings. For `IndexString`, it's a case insensitive comparison of the values, and this can be about 25% slower than `IndexBinary`.

I'm very surprised by how slow `IndexJSON` was for you. I have some ideas on why and there's probably some optimization that can be made. 

> Is the way to save BTree to file and read it? Are there hidden internal restrictions?

It's certainly possible to snapshot a BTree to disk and then reconstruct it in memory. Though I see two challenges with doing so in Bunt.

1. An index in Bunt can be application specific. The builtin `IndexString` and `IndexJSON` are helpers, but it's possible to create custom index such as an `IndexBSON` or `IndexMsgPack`. A future change to the logic of custom index in code may have side-effect with the saved index data that resides on disk.

2. Juggling two different data sets can be tough while maintaining the durability required by ACID.

That being said, it may be possible to overcome these concerns. I have to put more thought into it.

===

I would like to reproduce your results. The IndexJSON is very concerning. Could you provide an example JSON document? Also what is the average size of the keys and values used when creating and IndexString?

Thanks for a bunch for this info.

**Comment by k0mrade** [comment]
Hi,

I describe my task shortly in general. I would be obliged if you give me your opinion if you have time.I'm working on the wifi hotspot solution. The vendor Ruckus. Wifi controller has Northbound API, and it could work as a network access server. Unauthorized stations redirect to external web server and controller generates URL.

The first idea was to duplicate some data(such as SessionKey.StationMAC=SZURL.ClientMac) and place it to a key for simplicity. I sort SessionKey by field then count, search unique, etc. 

`https://10.0.0.253:9002/join?nbiIP=10.0.0.241&wlan=58&reason=Un-Auth-Captive&loc=4f6666696365&mac=6c:aa:b3:1b:fa:50&uip=ENC1bf058f5336ccb5e32d7046a0c3f5ea9&url=http%3A%2F%2Fmazda.ua%2F&zoneName=ON+AIR+Office&client_mac=ENCa09ad3bc1b0383ef61e611b452b69a78d4efdec5e514fdde&sip=194.242.99.241&proxy=0&ssid=9002&wlanName=9002&dn=`


```
// SessionKey ...
type SessionKey struct {
	AdID         string  
	ApMAC        string
	StationMAC   string
	StationIP    string
	AdShowTime   int64
	AdActionTime int64
}

// SessionValue ...
type SessionValue struct {
	AdShowTime   int64
	AdActionTime int64
	AdStopTime   int64 
	UserAgent    UserAgent
	SZUrl        SZURL
}

// SZURL generated by SZ
type SZURL struct {
	NbIP       string `schema:"nbiIP"`      // Northbound IP
	ClientMac  string `schema:"client_mac"` // Client MAC
	DomainName string `schema:"dn"`         // Domain name
	Loaction   string `schema:"loc"`        // Location
	MAC        string `schema:"mac"`        // Acccess point mac address
	Proxy      string `schema:"proxy"`
	Reason     string `schema:"reason"`
	Sip        string `schema:"sip"`
	SSID       string `schema:"ssid"`
	StartURL   string `schema:"startUrl"`
	UIP        string `schema:"uip"` 		// Station IP
	URL        string `schema:"url"`
	VLAN       string `schema:"vlan"`
	WLAN       string `schema:"wlan"`
	ZoneID     string `schema:"zoneId"`
	ZoneName   string `schema:"zoneName"`
}

// UserAgent ...
type UserAgent struct {
	OS           string
	Platform     string
	Engine       Engine
	Browser      Browser
	Localization string
}

// Engine ...
type Engine struct {
	Name    string
	Version string
}

// Browser ...
type Browser struct {
	Name    string
	Version string
}

```
I serialize key as

```
// SessionKeyToString ecodes SessionKey to a string session key
func SessionKeyToString(sk SessionKey) string {
	st := strconv.FormatInt(sk.AdShowTime, 10)
	at := strconv.FormatInt(sk.AdActionTime, 10)
	enc := sk.AdID + " " + sk.ApMAC + " " + sk.StationMAC + " " + sk.StationIP + " " + st + " " + at
	return enc
}
```

value as 

```
// EncodeSessionValue ecodes SessionValue to the bytes session value
func EncodeSessionValue(sv SessionValue) ([]byte, error) {
	enc, err := json.Marshal(sv)
	if err != nil {
		return nil, err
	}
	return enc, nil
}
```

It was very early implementation based on BoltDB. Now I try to find the solution that works with ~50K records per day. The index will be by 
WLAN
AdActionTime
AdID
MAC
ClientMac

I want to avoid using standalone databases if it is possible and move all computation into the golang code. Golang concurrency and fast search in BTree give me the potential possibility to manipulate with these data in real time on one side and simple deployment/support mechanism on another side.

About IndexJSON. I think standard golang json.Marshal/Unmarshal is slow. I try another lib such [ffjson](https://github.com/pquerna/ffjson) with BuntDB. It's faster(~ 2 times), but not so fast as I need 

I can share the database and the test code if you have time to advice to me.

**Comment by tidwall** [comment]
Thank you for sharing your architecture. I would very much like to have a snapshot of your database and test code. This would help with benchmarking and optimizing BuntDB. 

I just posted an update to BuntDB moments ago that speeds up IndexString nearly 2x.

I'm still looking into IndexJSON. I agree that it's the constant Marshal/Unmarshal code. There're too many redundant operations being made in the `indexJSON` function atm. I might be able to do some tricks to help speed this up.

Would it be an option for you to use a binary format such as BSON or MessagePack instead of JSON?

**Comment by tidwall** [comment]
I just released an update to BuntDB that processes JSON much faster. I created a new library [GJSON](https://github.com/tidwall/gjson) that I'm using specifically for high performance JSON indexing with BuntDB.

I hope you find this helpful. Thanks.

**Comment by tidwall** [comment]
I just pushed another update to BuntDB that speeds up loading from disk +25%.

**Comment by k0mrade** [comment]
Hi Josh,

thank you a lot for GJSON and another improvement. 
there are 4 errors, I think. I added some test into buntdb_test.go to the TestJSONIndex function.
AscendRange, AscendLessThan, DescendRange, DescendLessOrEqual don't return empty sets.

I dug to the btree iterate function, but I have not found mistake yet. Could you answer what does iterate function return (var hit and second bool)?

```
bash-3.2$ go test -test.run TestJSONIndex -v                                                                                                                      
=== RUN   TestJSONIndex                                                                                                                                                                                                                             
--- PASS: TestJSONIndex (0.00s)                                                                                                                                   
        buntdb_test.go:1633: []                                                                                                                                   
        buntdb_test.go:1640: []                                                                                                                                   
        buntdb_test.go:1647: []                                                                                                                                   
        buntdb_test.go:1654: []                                                                                                                                   
PASS                                                                                                                                                              
ok      github.com/tidwall/buntdb       0.007s 
```

```
// AscendRange test
var keys2 []string
_ = tx.AscendRange("age", "20", "30", func(key, value string) bool {
	keys2 = append(keys2, key)
	return true
})
t.Logf("%v\n", keys2)
// AscendLessThan test
var keys3 []string
_ = tx.AscendLessThan("age", "30", func(key, value string) bool {
	keys3 = append(keys3, value)
	return true
})
t.Logf("%v\n", keys3)
// DescendRange test
var keys4 []string
_ = tx.DescendRange("age", "20", "30", func(key, value string) bool {
	keys4 = append(keys4, key)
	return true
})
t.Logf("%v\n", keys4)
// DescendLessOrEqual test
var keys5 []string
_ = tx.DescendLessOrEqual("age", "20", func(key, value string) bool {
	keys5 = append(keys5, value)
	return true
})
t.Logf("%v\n", keys5)
```

**Comment by tidwall** [comment]
You need to pass in json that has an "age" field.

```go
_ = tx.AscendRange("age", `{"age":20}`, `{"age":30}`, func(key, value string) bool {
	keys2 = append(keys2, key)
	return true
})
t.Logf("%v\n", keys2)
// AscendLessThan test
var keys3 []string
_ = tx.AscendLessThan("age", `{"age":30}`, func(key, value string) bool {
	keys3 = append(keys3, value)
	return true
})
t.Logf("%v\n", keys3)
// DescendRange test
var keys4 []string
_ = tx.DescendRange("age", `{"age":20}`, `{"age":30}`, func(key, value string) bool {
	keys4 = append(keys4, key)
	return true
})
t.Logf("%v\n", keys4)
// DescendLessOrEqual test
var keys5 []string
_ = tx.DescendLessOrEqual("age", `{"age":20}`, func(key, value string) bool {
	keys5 = append(keys5, value)
	return true
})
```

**Comment by tidwall** [comment]
The Ascend* and Descend* functions traverse the btree in the same manner as the Get/Set/Del. And therefore they require a similar JSON document to compare the elements in the btree against.

**Comment by k0mrade** [comment]
Understood, thank you, Josh.

**Comment by tidwall** [comment]
You're welcome.

**Comment by tidwall** [comment]
Hi Dmitry, I'm closing this issue for now, but feel free to reopen if there's anything further that you need.
